<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="My-PC" name="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses" tests="30" failures="4" timestamp="1 Aug 2018 06:05:02 GMT" time="13.823" errors="0">
  <testcase name="clientMenu" time="1.301" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="clear" time="0.346" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="firstPageDisabled" time="0.348" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="profileMenu" time="0.029" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="taskresponses" time="0.955" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="userMenu" time="0.043" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="cvsexport" time="0.362" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="prevPageDisabled" time="0.327" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="lastPageDisabled" time="0.344" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="rewardpointsMenu" time="0.026" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="clickontaskResponses" time="0.746" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="Facebook_Logo" time="0.353" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses">
    <failure type="java.lang.AssertionError" message="expected [http://localhost:8090/Dmall/images/icon-fb.png] but found [http://localhost:9090/mystery/images/icon-fb.png]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost:8090/Dmall/images/icon-fb.png] but found [http://localhost:9090/mystery/images/icon-fb.png]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.ingecno.MysteryShoppers.taskTestCase.TaskResponses.Facebook_Logo(TaskResponses.java:314)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Facebook_Logo -->
  <testcase name="managetask" time="0.064" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="manageMenu" time="0.036" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="clickonbelowtask_taskResponses" time="0.360" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="filter" time="0.328" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="storedetails_TaskrRsponses" time="0.921" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses">
    <failure type="java.lang.AssertionError" message="expected [Store Details] but found [FAIL Object not found Unable to locate element: {&quot;method&quot;:&quot;xpath&quot;,&quot;selector&quot;:&quot;/html/body/div/div[3]/form/div/table/tbody[1]/tr/td/a&quot;}
Command duration or timeout: 54 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: &#039;2.52.0&#039;, revision: &#039;4c2593c&#039;, time: &#039;2016-02-11 19:06:42&#039;
System info: host: &#039;My-PC&#039;, ip: &#039;192.168.0.108&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.7.0_45&#039;
*** Element info: {Using=xpath, value=/html/body/div/div[3]/form/div/table/tbody[1]/tr/td/a}
Session ID: 43100d8b-9488-4a48-8ff7-5924b6aa489a
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=46.0.1}]]">
      <![CDATA[java.lang.AssertionError: expected [Store Details] but found [FAIL Object not found Unable to locate element: {"method":"xpath","selector":"/html/body/div/div[3]/form/div/table/tbody[1]/tr/td/a"}
Command duration or timeout: 54 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'My-PC', ip: '192.168.0.108', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_45'
*** Element info: {Using=xpath, value=/html/body/div/div[3]/form/div/table/tbody[1]/tr/td/a}
Session ID: 43100d8b-9488-4a48-8ff7-5924b6aa489a
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=46.0.1}]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.ingecno.MysteryShoppers.taskTestCase.TaskResponses.storedetails_TaskrRsponses(TaskResponses.java:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- storedetails_TaskrRsponses -->
  <testcase name="xlsexport" time="0.356" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="credential" time="3.799" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="reportsMenu" time="0.027" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="nextPageDisabled" time="0.348" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="selectRows" time="0.373" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="twitter_logo" time="0.346" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses">
    <failure type="java.lang.AssertionError" message="expected [http://localhost:8090/Dmall/images/icon-tw.png] but found [http://localhost:9090/mystery/images/icon-tw.png]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost:8090/Dmall/images/icon-tw.png] but found [http://localhost:9090/mystery/images/icon-tw.png]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.ingecno.MysteryShoppers.taskTestCase.TaskResponses.twitter_logo(TaskResponses.java:326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- twitter_logo -->
  <testcase name="Pagetitle_taskresponses" time="0.561" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="taskMenu" time="0.030" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="taskIdFilter" time="0.350" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="in_logo" time="0.344" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses">
    <failure type="java.lang.AssertionError" message="expected [http://localhost:8090/Dmall/images/icon-in.png] but found [http://localhost:9090/mystery/images/icon-in.png]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost:8090/Dmall/images/icon-in.png] but found [http://localhost:9090/mystery/images/icon-in.png]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.ingecno.MysteryShoppers.taskTestCase.TaskResponses.in_logo(TaskResponses.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- in_logo -->
  <testcase name="logoutMenu" time="0.025" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="feebackMenu" time="0.029" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
  <testcase name="pdfexport" time="0.346" classname="com.ingecno.MysteryShoppers.taskTestCase.TaskResponses"/>
</testsuite> <!-- com.ingecno.MysteryShoppers.taskTestCase.TaskResponses -->
